"""empty message

Revision ID: 02c3c14cf963
Revises: 5bd4c055282c
Create Date: 2019-10-24 16:31:10.834322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c3c14cf963'
down_revision = '5bd4c055282c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article') as batch_op:
        batch_op.drop_column('article', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('note', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
