"""empty message

Revision ID: 141c8b6ac42e
Revises: b8008a537fe8
Create Date: 2019-10-24 16:39:34.979509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141c8b6ac42e'
down_revision = 'b8008a537fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('note', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
