"""empty message

Revision ID: 5bd4c055282c
Revises: 37b052c700d4
Create Date: 2019-10-24 16:23:25.627528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd4c055282c'
down_revision = '37b052c700d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('note', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
