"""empty message

Revision ID: 74bb7726e884
Revises: c01e51e50b7e
Create Date: 2019-10-24 12:08:26.479218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74bb7726e884'
down_revision = 'c01e51e50b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('notes', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
