"""empty message

Revision ID: 7cb1f8461010
Revises: 7d960b214cd2
Create Date: 2019-10-24 12:39:33.904397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb1f8461010'
down_revision = '7d960b214cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'article',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('article', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('notes', sa.VARCHAR(length=1000), nullable=True))
    op.alter_column('article', 'article',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
