"""empty message

Revision ID: 955b2161e2b5
Revises: 
Create Date: 2019-10-21 09:06:07.148807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955b2161e2b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('notes', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
