"""empty message

Revision ID: b8008a537fe8
Revises: 02c3c14cf963
Create Date: 2019-10-24 16:37:16.713156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8008a537fe8'
down_revision = '02c3c14cf963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('note', sa.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
