"""empty message

Revision ID: c01e51e50b7e
Revises: db740a8addb8
Create Date: 2019-10-23 21:27:01.934728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01e51e50b7e'
down_revision = 'db740a8addb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('summary', sa.String(length=500), nullable=True))
    op.drop_column('article', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('notes', sa.VARCHAR(length=1000), nullable=True))
    op.drop_column('article', 'summary')
    # ### end Alembic commands ###
