"""empty message

Revision ID: e4b8ec7fc016
Revises: a3355fa45ec8
Create Date: 2019-10-25 23:51:31.587624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b8ec7fc016'
down_revision = 'a3355fa45ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'url')
    # ### end Alembic commands ###
